# Generated by Django 2.1.10 on 2019-10-29 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_auto_20191029_1739'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PointsOwned',
            new_name='PointsOwnedTransaction',
        ),
        migrations.RenameModel(
            old_name='PointsAccount',
            new_name='PointsToDonateTransaction',
        ),
    ]
