# Generated by Django 2.1.10 on 2019-10-29 23:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_auto_20191029_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsToDonateMonthBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_remaining', models.IntegerField()),
                ('date_begin', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('date_expire', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.PointsUser')),
            ],
        ),
        migrations.RemoveField(
            model_name='pointstodonatetransaction',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='pointsownedtransaction',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='pointsownedtransaction',
            name='amount_transacted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pointsownedtransaction',
            name='donator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donator', to='Accounts.PointsUser'),
        ),
        migrations.AlterField(
            model_name='pointsownedtransaction',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='Accounts.PointsUser'),
        ),
        migrations.DeleteModel(
            name='PointsToDonateTransaction',
        ),
    ]
