# Generated by Django 2.1.10 on 2019-11-04 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_auto_20191029_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointsownedtransaction',
            name='donator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donation_set', to='Accounts.PointsUser'),
        ),
        migrations.AlterField(
            model_name='pointsownedtransaction',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_points_set', to='Accounts.PointsUser'),
        ),
    ]
